/**
 * AppStorage key名称枚举
 */
export enum TnAppStorageKey {
  /**
   * 全局基础样式
   */
  BASE_STYLE = "TnBaseStyle",
  /**
   * 是否横屏
   */
  IS_LANDSCAPE = 'TnIsLandscape',
  /**
   * 顶部规避尺寸
   */
  TOP_AVOID_HEIGHT = 'TnTopAvoidHeight',
  /**
   * 底部导航条高度
   */
  BOTTOM_BAR_HEIGHT = 'TnBottomBarHeight',
  /**
   * 键盘高度
   */
  KEYBOARD_HEIGHT = 'TnKeyBoardHeight',
  /**
   * 颜色模式
   */
  COLOR_MODE = 'TnColorMode',
  /**
   * 语言
   */
  LANGUAGE = 'TnLanguage',
  /**
   * 全局配置
   */
  GLOBAL_CONFIG = 'TnGlobalConfig'
}