/**
 * @file 主模块路由定义
 * @author JunBin.Yang
 */
export class MainRoutes {
  /**
   * 主框架路由
   */
  static Main = "main/main";
  /**
   * 样式展示页面路由
   */
  static Style = "main/style";
  /**
   * 主题颜色展示页面路由
   */
  static ThemeColor = "main/theme-color";
  /**
   * 内置颜色展示页面路由
   */
  static BuiltInColor = "main/builtin-color";
  /**
   * 渐变背景展示页面路由
   */
  static GradientBackground = "main/gradient-background";
  /**
   * 字体大小展示页面路由
   */
  static FontSize = "main/font-size";
  /**
   * 间距展示页面路由
   */
  static Spacing = "main/spacing";
  /**
   * 尺寸展示页面路由
   */
  static Size = "main/size";
  /**
   * 主题切换展示页面路由
   */
  static TnTheme = "main/tn-theme";
  /**
   * 图标展示页面路由
   */
  static TnIcon = "main/tn-icon";
  /**
   * 按钮展示页面路由
   */
  static TnButton = "main/tn-button";
  /**
   * 标签展示页面路由
   */
  static TnTag = "main/tn-tag";
  /**
   * 徽标展示页面路由
   */
  static TnBadge = "main/tn-badge";
  /**
   * 加载展示页面路由
   */
  static TnLoading = "main/tn-loading";
  /**
   * 开关展示页面路由
   */
  static TnSwitch = "main/tn-switch";
  /**
   * 单选框展示页面路由
   */
  static TnRadio = "main/tn-radio";
  /**
   * 复选框展示页面路由
   */
  static TnCheckbox = "main/tn-checkbox";
  /**
   * 评分展示页面路由
   */
  static TnRate = "main/tn-rate";
  /**
   * 输入框展示页面路由
   */
  static TnInput = "main/tn-input";
  /**
   * 步进器展示页面路由
   */
  static TnNumberBox = "main/tn-number-box";
  /**
   * 滑块展示页面路由
   */
  static TnSlider = "main/tn-slider";
  /**
   * 选择器展示页面路由
   */
  static TnPicker = "main/tn-picker";
  /**
   * 日期时间选择器展示页面路由
   */
  static TnDateTimePicker = "main/tn-date-time-picker";
  /**
   * 地区选择器展示页面路由
   */
  static TnRegionPicker = "main/tn-region-picker";
  /**
   * 图片上传展示页面路由
   */
  static TnImageUpload = "main/tn-image-upload";
  /**
   * 日历展示页面路由
   */
  static TnCalendar = "main/tn-calendar";
  /**
   * 周日历展示页面路由
   */
  static TnWeekCalendar = "main/tn-week-calendar";
  /**
   * 表单展示页面路由
   */
  static TnForm = "main/tn-form";
  /**
   * 图片预览展示页面路由
   */
  static TnImagePreview = "main/tn-image-preview";
  /**
   * 弹出框展示页面路由
   */
  static TnPopup = "main/tn-popup";
  /**
   * 列表展示页面路由
   */
  static TnList = "main/tn-list";
  /**
   * 阴影展示页面路由
   */
  static Shadow = "main/shadow";
  /**
   * 毛玻璃效果展示页面路由
   */
  static BlurEffect = "main/blur-effect";
}